### ISSUE TITLE
#to_s doesn't round-trip for some values

### ISSUE THREAD

**Issue by pivotale20** [minad/unit#22]
```ruby
Unit(1, 2, "m") # => Unit("1/2 m")
Unit("1/2 m") # => Unit("1/2 m^-1")
```

**Comment by fordhurley** [comment]
I ran into this problem after doing some arithmetic operations on units. For example:

```ruby
a = Unit('5 cm')
b = Unit('1 cm')
c = a - b # => Unit("4/1 cm")
c.to_s # => "4/1 cm"
Unit(c.to_s) # => Unit("4 cm^-1")
```

It makes sense that `"4/1 cm"` needs to be parsed as `"4 / (1 cm)"`, for correct operator precedence. The problem to me is that `#to_s` isn't outputting a string that can be properly parsed. If it included the necessary parentheses, that would solve it. E.g., `"(4/1) cm"`. (In this particular case, reducing the fraction would be even better...)

**Comment by fordhurley** [comment]
PR #26 solves the issues I was having, and should solve @pivotale20's issue, too.

```ruby
a = Unit('5 cm')
b = Unit('1 cm')
c = a - b # => Unit("4 cm")
c.to_s # => "4 cm"
Unit(c.to_s) # => Unit("4 cm")
```

and

```ruby
Unit(1, 2, "m") # => Unit("(1/2) m")
Unit("(1/2) m") # => Unit("(1/2) m")
```

More generally, this should hold:

```ruby
Unit(unit.to_s) == unit
```
